services:
  webapi:
    image: api-parcking
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - AdminSettings__Password=${AdminSettings__Password}
      - SmtpSettings__Password=${SmtpSettings__Password}
    ports:
      - "8080:8080"
